# -- Custom labels to add into metadata
customLabels: {}

podLabels: {}

image:
  repository: "public.ecr.aws/waltju/kscu"
  tag: "1.7"
  pullPolicy: IfNotPresent

taintKey: "example.com/kubelet-no-server-cert"
checkInterval: 5
logLevel: 4

resources:
  limits:
    cpu: 10m
    memory: 80Mi
  requests:
    cpu: 10m
    memory: 80Mi

nodeAffinity: {}

tolerations:
  - effect: NoSchedule
    operator: Exists
  - effect: NoExecute
    operator: Exists
